//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalyFarmar.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BuyPageStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BuyPageStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MalyFarmar.Resources.Strings.BuyPageStrings", typeof(BuyPageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BuyPageTitle {
            get {
                return ResourceManager.GetString("BuyPageTitle", resourceCulture);
            }
        }
        
        internal static string StatusNoProductsAvailable {
            get {
                return ResourceManager.GetString("StatusNoProductsAvailable", resourceCulture);
            }
        }
        
        internal static string StatusUnexpectedErrorPrefix {
            get {
                return ResourceManager.GetString("StatusUnexpectedErrorPrefix", resourceCulture);
            }
        }
        
        internal static string StatusFailedToLoadProductsPrefix {
            get {
                return ResourceManager.GetString("StatusFailedToLoadProductsPrefix", resourceCulture);
            }
        }
        
        internal static string StatusLoadingCancelled {
            get {
                return ResourceManager.GetString("StatusLoadingCancelled", resourceCulture);
            }
        }
        
        internal static string StatusNoProductsFound {
            get {
                return ResourceManager.GetString("StatusNoProductsFound", resourceCulture);
            }
        }
        
        internal static string StatusLocationUnavailable {
            get {
                return ResourceManager.GetString("StatusLocationUnavailable", resourceCulture);
            }
        }
        
        internal static string StatusCurrentUserError {
            get {
                return ResourceManager.GetString("StatusCurrentUserError", resourceCulture);
            }
        }
    }
}
