//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalyFarmar.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MalyFarmar.Resources.Strings.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        internal static string LocationAcquiredMessage {
            get {
                return ResourceManager.GetString("LocationAcquiredMessage", resourceCulture);
            }
        }
        
        internal static string UnableToRetrieveLocationMessage {
            get {
                return ResourceManager.GetString("UnableToRetrieveLocationMessage", resourceCulture);
            }
        }
        
        internal static string LocationPermissionDeniedMessage {
            get {
                return ResourceManager.GetString("LocationPermissionDeniedMessage", resourceCulture);
            }
        }
        
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        internal static string LocationServicesNotEnabledMessage {
            get {
                return ResourceManager.GetString("LocationServicesNotEnabledMessage", resourceCulture);
            }
        }
        
        internal static string LocationPermissionNotGrantedMessage {
            get {
                return ResourceManager.GetString("LocationPermissionNotGrantedMessage", resourceCulture);
            }
        }
        
        internal static string LocationNotSupportedMessage {
            get {
                return ResourceManager.GetString("LocationNotSupportedMessage", resourceCulture);
            }
        }
        
        internal static string ServerErrorMessage {
            get {
                return ResourceManager.GetString("ServerErrorMessage", resourceCulture);
            }
        }
        
        internal static string InvalidDataMessage {
            get {
                return ResourceManager.GetString("InvalidDataMessage", resourceCulture);
            }
        }
        
        internal static string ValidationErrorsMessage {
            get {
                return ResourceManager.GetString("ValidationErrorsMessage", resourceCulture);
            }
        }
        
        internal static string UnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("UnexpectedErrorMessage", resourceCulture);
            }
        }
    }
}
