//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalyFarmar.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreateUserPageStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateUserPageStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MalyFarmar.Resources.Strings.CreateUserPageStrings", typeof(CreateUserPageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        internal static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        internal static string PhoneNumberLabel {
            get {
                return ResourceManager.GetString("PhoneNumberLabel", resourceCulture);
            }
        }
        
        internal static string DeviceLocationLabel {
            get {
                return ResourceManager.GetString("DeviceLocationLabel", resourceCulture);
            }
        }
        
        internal static string GetCurrentLocationButtonText {
            get {
                return ResourceManager.GetString("GetCurrentLocationButtonText", resourceCulture);
            }
        }
        
        internal static string CreateAccountButtonText {
            get {
                return ResourceManager.GetString("CreateAccountButtonText", resourceCulture);
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("FirstNamePlaceholder", resourceCulture);
            }
        }
        
        internal static string LastNamePlaceholder {
            get {
                return ResourceManager.GetString("LastNamePlaceholder", resourceCulture);
            }
        }
        
        internal static string PhoneNumberPlaceholder {
            get {
                return ResourceManager.GetString("PhoneNumberPlaceholder", resourceCulture);
            }
        }
        
        internal static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        internal static string FirstNameRequiredMessage {
            get {
                return ResourceManager.GetString("FirstNameRequiredMessage", resourceCulture);
            }
        }
        
        internal static string LastNameRequiredMessage {
            get {
                return ResourceManager.GetString("LastNameRequiredMessage", resourceCulture);
            }
        }
        
        internal static string EmailRequiredMessage {
            get {
                return ResourceManager.GetString("EmailRequiredMessage", resourceCulture);
            }
        }
        
        internal static string PhoneNumberRequiredMessage {
            get {
                return ResourceManager.GetString("PhoneNumberRequiredMessage", resourceCulture);
            }
        }
        
        internal static string InvalidEmailMessage {
            get {
                return ResourceManager.GetString("InvalidEmailMessage", resourceCulture);
            }
        }
        
        internal static string CorrectTheHighlightedFieldsMessage {
            get {
                return ResourceManager.GetString("CorrectTheHighlightedFieldsMessage", resourceCulture);
            }
        }
        
        internal static string AccountCreatedAlertDescription {
            get {
                return ResourceManager.GetString("AccountCreatedAlertDescription", resourceCulture);
            }
        }
        
        internal static string FailedToCreateAccountMessage {
            get {
                return ResourceManager.GetString("FailedToCreateAccountMessage", resourceCulture);
            }
        }
    }
}
