//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalyFarmar.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreateProductPageStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateProductPageStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MalyFarmar.Resources.Strings.CreateProductPageStrings", typeof(CreateProductPageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string LabelProductName {
            get {
                return ResourceManager.GetString("LabelProductName", resourceCulture);
            }
        }
        
        internal static string PlaceholderProductName {
            get {
                return ResourceManager.GetString("PlaceholderProductName", resourceCulture);
            }
        }
        
        internal static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        internal static string PlaceholderDescription {
            get {
                return ResourceManager.GetString("PlaceholderDescription", resourceCulture);
            }
        }
        
        internal static string LabelTotalAmount {
            get {
                return ResourceManager.GetString("LabelTotalAmount", resourceCulture);
            }
        }
        
        internal static string PlaceholderTotalAmount {
            get {
                return ResourceManager.GetString("PlaceholderTotalAmount", resourceCulture);
            }
        }
        
        internal static string LabelUnit {
            get {
                return ResourceManager.GetString("LabelUnit", resourceCulture);
            }
        }
        
        internal static string PlaceholderUnit {
            get {
                return ResourceManager.GetString("PlaceholderUnit", resourceCulture);
            }
        }
        
        internal static string LabelPricePerUnit {
            get {
                return ResourceManager.GetString("LabelPricePerUnit", resourceCulture);
            }
        }
        
        internal static string PlaceholderPricePerUnit {
            get {
                return ResourceManager.GetString("PlaceholderPricePerUnit", resourceCulture);
            }
        }
        
        internal static string LabelProductImage {
            get {
                return ResourceManager.GetString("LabelProductImage", resourceCulture);
            }
        }
        
        internal static string LabelSelectImage {
            get {
                return ResourceManager.GetString("LabelSelectImage", resourceCulture);
            }
        }
        
        internal static string ButtonSelectImage {
            get {
                return ResourceManager.GetString("ButtonSelectImage", resourceCulture);
            }
        }
        
        internal static string ButtonAddProduct {
            get {
                return ResourceManager.GetString("ButtonAddProduct", resourceCulture);
            }
        }
        
        internal static string ErrorPickingImagePrefix {
            get {
                return ResourceManager.GetString("ErrorPickingImagePrefix", resourceCulture);
            }
        }
        
        internal static string ErrorProcessingImagePrefix {
            get {
                return ResourceManager.GetString("ErrorProcessingImagePrefix", resourceCulture);
            }
        }
        
        internal static string ErrorCurrentUser {
            get {
                return ResourceManager.GetString("ErrorCurrentUser", resourceCulture);
            }
        }
        
        internal static string AlertCreateSuccessTitle {
            get {
                return ResourceManager.GetString("AlertCreateSuccessTitle", resourceCulture);
            }
        }
        
        internal static string AlertCreateSuccessMessageFormat {
            get {
                return ResourceManager.GetString("AlertCreateSuccessMessageFormat", resourceCulture);
            }
        }
        
        internal static string ErrorCreateFailedUnexpectedResponse {
            get {
                return ResourceManager.GetString("ErrorCreateFailedUnexpectedResponse", resourceCulture);
            }
        }
        
        internal static string ErrorCreateFailedPrefix {
            get {
                return ResourceManager.GetString("ErrorCreateFailedPrefix", resourceCulture);
            }
        }
        
        internal static string ValidationNameRequired {
            get {
                return ResourceManager.GetString("ValidationNameRequired", resourceCulture);
            }
        }
        
        internal static string ValidationUnitRequired {
            get {
                return ResourceManager.GetString("ValidationUnitRequired", resourceCulture);
            }
        }
        
        internal static string ValidationTotalAmountInvalid {
            get {
                return ResourceManager.GetString("ValidationTotalAmountInvalid", resourceCulture);
            }
        }
        
        internal static string ValidationPricePerUnitInvalid {
            get {
                return ResourceManager.GetString("ValidationPricePerUnitInvalid", resourceCulture);
            }
        }
        
        internal static string ErrorUnexpectedPrefix {
            get {
                return ResourceManager.GetString("ErrorUnexpectedPrefix", resourceCulture);
            }
        }
    }
}
