//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalyFarmar.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditProductPageStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditProductPageStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MalyFarmar.Resources.Strings.EditProductPageStrings", typeof(EditProductPageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string LabelProductName {
            get {
                return ResourceManager.GetString("LabelProductName", resourceCulture);
            }
        }
        
        internal static string PlaceholderProductName {
            get {
                return ResourceManager.GetString("PlaceholderProductName", resourceCulture);
            }
        }
        
        internal static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        internal static string PlaceholderDescription {
            get {
                return ResourceManager.GetString("PlaceholderDescription", resourceCulture);
            }
        }
        
        internal static string LabelTotalAmount {
            get {
                return ResourceManager.GetString("LabelTotalAmount", resourceCulture);
            }
        }
        
        internal static string PlaceholderTotalAmount {
            get {
                return ResourceManager.GetString("PlaceholderTotalAmount", resourceCulture);
            }
        }
        
        internal static string LabelPricePerUnit {
            get {
                return ResourceManager.GetString("LabelPricePerUnit", resourceCulture);
            }
        }
        
        internal static string PlaceholderPricePerUnit {
            get {
                return ResourceManager.GetString("PlaceholderPricePerUnit", resourceCulture);
            }
        }
        
        internal static string ButtonSaveChanges {
            get {
                return ResourceManager.GetString("ButtonSaveChanges", resourceCulture);
            }
        }
        
        internal static string ButtonDeleteProduct {
            get {
                return ResourceManager.GetString("ButtonDeleteProduct", resourceCulture);
            }
        }
        
        internal static string ErrorProductNotFound {
            get {
                return ResourceManager.GetString("ErrorProductNotFound", resourceCulture);
            }
        }
        
        internal static string ErrorFailedToLoadProductPrefix {
            get {
                return ResourceManager.GetString("ErrorFailedToLoadProductPrefix", resourceCulture);
            }
        }
        
        internal static string ValidationNameRequired {
            get {
                return ResourceManager.GetString("ValidationNameRequired", resourceCulture);
            }
        }
        
        internal static string ValidationTotalAmountInvalid {
            get {
                return ResourceManager.GetString("ValidationTotalAmountInvalid", resourceCulture);
            }
        }
        
        internal static string ValidationPricePerUnitInvalid {
            get {
                return ResourceManager.GetString("ValidationPricePerUnitInvalid", resourceCulture);
            }
        }
        
        internal static string ValidationTotalAmountTooLowFormat {
            get {
                return ResourceManager.GetString("ValidationTotalAmountTooLowFormat", resourceCulture);
            }
        }
        
        internal static string AlertUpdateSuccessTitle {
            get {
                return ResourceManager.GetString("AlertUpdateSuccessTitle", resourceCulture);
            }
        }
        
        internal static string AlertUpdateSuccessMessage {
            get {
                return ResourceManager.GetString("AlertUpdateSuccessMessage", resourceCulture);
            }
        }
        
        internal static string AlertUpdateFailedPrefix {
            get {
                return ResourceManager.GetString("AlertUpdateFailedPrefix", resourceCulture);
            }
        }
        
        internal static string AlertDeleteConfirmTitle {
            get {
                return ResourceManager.GetString("AlertDeleteConfirmTitle", resourceCulture);
            }
        }
        
        internal static string AlertDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("AlertDeleteConfirmMessage", resourceCulture);
            }
        }
        
        internal static string AlertDeleteConfirmYes {
            get {
                return ResourceManager.GetString("AlertDeleteConfirmYes", resourceCulture);
            }
        }
        
        internal static string AlertDeleteConfirmCancel {
            get {
                return ResourceManager.GetString("AlertDeleteConfirmCancel", resourceCulture);
            }
        }
        
        internal static string AlertDeleteSuccessTitle {
            get {
                return ResourceManager.GetString("AlertDeleteSuccessTitle", resourceCulture);
            }
        }
        
        internal static string AlertDeleteSuccessMessage {
            get {
                return ResourceManager.GetString("AlertDeleteSuccessMessage", resourceCulture);
            }
        }
        
        internal static string AlertDeleteFailedPrefix {
            get {
                return ResourceManager.GetString("AlertDeleteFailedPrefix", resourceCulture);
            }
        }
        
        internal static string ErrorUnexpectedPrefix {
            get {
                return ResourceManager.GetString("ErrorUnexpectedPrefix", resourceCulture);
            }
        }
    }
}
