//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalyFarmar.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocationStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocationStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MalyFarmar.Resources.Strings.LocationStrings", typeof(LocationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LocationPermissionDeniedMessage {
            get {
                return ResourceManager.GetString("LocationPermissionDeniedMessage", resourceCulture);
            }
        }
        
        internal static string UnableToRetrieveLocationMessage {
            get {
                return ResourceManager.GetString("UnableToRetrieveLocationMessage", resourceCulture);
            }
        }
        
        internal static string LocationAcquiredMessage {
            get {
                return ResourceManager.GetString("LocationAcquiredMessage", resourceCulture);
            }
        }
        
        internal static string LocationNotSupportedMessage {
            get {
                return ResourceManager.GetString("LocationNotSupportedMessage", resourceCulture);
            }
        }
        
        internal static string LocationServicesNotEnabledMessage {
            get {
                return ResourceManager.GetString("LocationServicesNotEnabledMessage", resourceCulture);
            }
        }
        
        internal static string LocationPermissionNotGrantedMessage {
            get {
                return ResourceManager.GetString("LocationPermissionNotGrantedMessage", resourceCulture);
            }
        }
    }
}
