//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalyFarmar.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoginPageStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginPageStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MalyFarmar.Resources.Strings.LoginPageStrings", typeof(LoginPageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string SignInLabel {
            get {
                return ResourceManager.GetString("SignInLabel", resourceCulture);
            }
        }
        
        internal static string CreateNewUserLabel {
            get {
                return ResourceManager.GetString("CreateNewUserLabel", resourceCulture);
            }
        }
        
        internal static string ErrorLoadingUsersAlertTitle {
            get {
                return ResourceManager.GetString("ErrorLoadingUsersAlertTitle", resourceCulture);
            }
        }
        
        internal static string ErrorLoadingUsersAlertDescription {
            get {
                return ResourceManager.GetString("ErrorLoadingUsersAlertDescription", resourceCulture);
            }
        }
        
        internal static string SelectUserAlertTitle {
            get {
                return ResourceManager.GetString("SelectUserAlertTitle", resourceCulture);
            }
        }
        
        internal static string SelectUserAlertDescription {
            get {
                return ResourceManager.GetString("SelectUserAlertDescription", resourceCulture);
            }
        }
    }
}
