//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalyFarmar.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyOrderDetailPageStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyOrderDetailPageStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MalyFarmar.Resources.Strings.MyOrderDetailPageStrings", typeof(MyOrderDetailPageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LabelSeller {
            get {
                return ResourceManager.GetString("LabelSeller", resourceCulture);
            }
        }
        
        internal static string LabelBuyer {
            get {
                return ResourceManager.GetString("LabelBuyer", resourceCulture);
            }
        }
        
        internal static string LabelItems {
            get {
                return ResourceManager.GetString("LabelItems", resourceCulture);
            }
        }
        
        internal static string LabelPickUpAt {
            get {
                return ResourceManager.GetString("LabelPickUpAt", resourceCulture);
            }
        }
        
        internal static string ButtonCancelOrderText {
            get {
                return ResourceManager.GetString("ButtonCancelOrderText", resourceCulture);
            }
        }
        
        internal static string ErrorOrderIdInvalid {
            get {
                return ResourceManager.GetString("ErrorOrderIdInvalid", resourceCulture);
            }
        }
        
        internal static string ErrorOrderNotFound {
            get {
                return ResourceManager.GetString("ErrorOrderNotFound", resourceCulture);
            }
        }
        
        internal static string ErrorNotBuyer {
            get {
                return ResourceManager.GetString("ErrorNotBuyer", resourceCulture);
            }
        }
        
        internal static string ErrorFailedToLoadOrderPrefix {
            get {
                return ResourceManager.GetString("ErrorFailedToLoadOrderPrefix", resourceCulture);
            }
        }
        
        internal static string ErrorUnexpectedPrefix {
            get {
                return ResourceManager.GetString("ErrorUnexpectedPrefix", resourceCulture);
            }
        }
        
        internal static string ErrorFailedToCancelPrefix {
            get {
                return ResourceManager.GetString("ErrorFailedToCancelPrefix", resourceCulture);
            }
        }
    }
}
