//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalyFarmar.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyReservationsPageStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyReservationsPageStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MalyFarmar.Resources.Strings.MyReservationsPageStrings", typeof(MyReservationsPageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string LabelReservationId {
            get {
                return ResourceManager.GetString("LabelReservationId", resourceCulture);
            }
        }
        
        internal static string LabelPickUpAt {
            get {
                return ResourceManager.GetString("LabelPickUpAt", resourceCulture);
            }
        }
        
        internal static string LabelStatus {
            get {
                return ResourceManager.GetString("LabelStatus", resourceCulture);
            }
        }
        
        internal static string LabelTotalPrice {
            get {
                return ResourceManager.GetString("LabelTotalPrice", resourceCulture);
            }
        }
        
        internal static string LabelCreatedAt {
            get {
                return ResourceManager.GetString("LabelCreatedAt", resourceCulture);
            }
        }
        
        internal static string LabelNotSet {
            get {
                return ResourceManager.GetString("LabelNotSet", resourceCulture);
            }
        }
        
        internal static string StatusCurrentUserError {
            get {
                return ResourceManager.GetString("StatusCurrentUserError", resourceCulture);
            }
        }
        
        internal static string StatusNoReservations {
            get {
                return ResourceManager.GetString("StatusNoReservations", resourceCulture);
            }
        }
        
        internal static string StatusNoReservationsFoundOrError {
            get {
                return ResourceManager.GetString("StatusNoReservationsFoundOrError", resourceCulture);
            }
        }
        
        internal static string StatusFailedToLoadPrefix {
            get {
                return ResourceManager.GetString("StatusFailedToLoadPrefix", resourceCulture);
            }
        }
        
        internal static string StatusUnexpectedErrorPrefix {
            get {
                return ResourceManager.GetString("StatusUnexpectedErrorPrefix", resourceCulture);
            }
        }
        
        internal static string StatusLoadingCancelled {
            get {
                return ResourceManager.GetString("StatusLoadingCancelled", resourceCulture);
            }
        }
        
        internal static string OrderStatusCreated {
            get {
                return ResourceManager.GetString("OrderStatusCreated", resourceCulture);
            }
        }
        
        internal static string OrderStatusPickUpSet {
            get {
                return ResourceManager.GetString("OrderStatusPickUpSet", resourceCulture);
            }
        }
        
        internal static string OrderStatusCompleted {
            get {
                return ResourceManager.GetString("OrderStatusCompleted", resourceCulture);
            }
        }
        
        internal static string OrderStatusUnknown {
            get {
                return ResourceManager.GetString("OrderStatusUnknown", resourceCulture);
            }
        }
    }
}
