//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalyFarmar.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrderDetailPageStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderDetailPageStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MalyFarmar.Resources.Strings.OrderDetailPageStrings", typeof(OrderDetailPageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string LabelOrderId {
            get {
                return ResourceManager.GetString("LabelOrderId", resourceCulture);
            }
        }
        
        internal static string LabelStatus {
            get {
                return ResourceManager.GetString("LabelStatus", resourceCulture);
            }
        }
        
        internal static string LabelTotalPrice {
            get {
                return ResourceManager.GetString("LabelTotalPrice", resourceCulture);
            }
        }
        
        internal static string LabelCreatedAt {
            get {
                return ResourceManager.GetString("LabelCreatedAt", resourceCulture);
            }
        }
        
        internal static string LabelPickUpAt {
            get {
                return ResourceManager.GetString("LabelPickUpAt", resourceCulture);
            }
        }
        
        internal static string LabelPickUpDate {
            get {
                return ResourceManager.GetString("LabelPickUpDate", resourceCulture);
            }
        }
        
        internal static string LabelPickUpTime {
            get {
                return ResourceManager.GetString("LabelPickUpTime", resourceCulture);
            }
        }
        
        internal static string LabelBuyerInfo {
            get {
                return ResourceManager.GetString("LabelBuyerInfo", resourceCulture);
            }
        }
        
        internal static string LabelItems {
            get {
                return ResourceManager.GetString("LabelItems", resourceCulture);
            }
        }
        
        internal static string LabelProductName {
            get {
                return ResourceManager.GetString("LabelProductName", resourceCulture);
            }
        }
        
        internal static string LabelAmount {
            get {
                return ResourceManager.GetString("LabelAmount", resourceCulture);
            }
        }
        
        internal static string LabelPrice {
            get {
                return ResourceManager.GetString("LabelPrice", resourceCulture);
            }
        }
        
        internal static string LabelSubtotal {
            get {
                return ResourceManager.GetString("LabelSubtotal", resourceCulture);
            }
        }
        
        internal static string ButtonSetPickUp {
            get {
                return ResourceManager.GetString("ButtonSetPickUp", resourceCulture);
            }
        }
        
        internal static string ButtonCompleteOrder {
            get {
                return ResourceManager.GetString("ButtonCompleteOrder", resourceCulture);
            }
        }
        
        internal static string ErrorOrderNotFound {
            get {
                return ResourceManager.GetString("ErrorOrderNotFound", resourceCulture);
            }
        }
        
        internal static string ErrorFailedToLoadDetailsPrefix {
            get {
                return ResourceManager.GetString("ErrorFailedToLoadDetailsPrefix", resourceCulture);
            }
        }
        
        internal static string ErrorPickUpTimeInPast {
            get {
                return ResourceManager.GetString("ErrorPickUpTimeInPast", resourceCulture);
            }
        }
        
        internal static string ErrorSettingPickUpTimePrefix {
            get {
                return ResourceManager.GetString("ErrorSettingPickUpTimePrefix", resourceCulture);
            }
        }
        
        internal static string ErrorCompletingOrderPrefix {
            get {
                return ResourceManager.GetString("ErrorCompletingOrderPrefix", resourceCulture);
            }
        }
        
        internal static string AlertPickUpSetSuccess {
            get {
                return ResourceManager.GetString("AlertPickUpSetSuccess", resourceCulture);
            }
        }
        
        internal static string AlertOrderCompletedSuccess {
            get {
                return ResourceManager.GetString("AlertOrderCompletedSuccess", resourceCulture);
            }
        }
        
        internal static string ValueNotSet {
            get {
                return ResourceManager.GetString("ValueNotSet", resourceCulture);
            }
        }
        
        internal static string AlertFinishConfirmTitle {
            get {
                return ResourceManager.GetString("AlertFinishConfirmTitle", resourceCulture);
            }
        }
        
        internal static string AlertFinishConfirmMessage {
            get {
                return ResourceManager.GetString("AlertFinishConfirmMessage", resourceCulture);
            }
        }
        
        internal static string AlertFinishConfirmYes {
            get {
                return ResourceManager.GetString("AlertFinishConfirmYes", resourceCulture);
            }
        }
        
        internal static string AlertFinishConfirmCancel {
            get {
                return ResourceManager.GetString("AlertFinishConfirmCancel", resourceCulture);
            }
        }
    }
}
