//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalyFarmar.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProductDetailPageStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductDetailPageStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MalyFarmar.Resources.Strings.ProductDetailPageStrings", typeof(ProductDetailPageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitleFallback {
            get {
                return ResourceManager.GetString("PageTitleFallback", resourceCulture);
            }
        }
        
        internal static string ToolbarItemEditText {
            get {
                return ResourceManager.GetString("ToolbarItemEditText", resourceCulture);
            }
        }
        
        internal static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        internal static string DescriptionNotAvailable {
            get {
                return ResourceManager.GetString("DescriptionNotAvailable", resourceCulture);
            }
        }
        
        internal static string LabelPrice {
            get {
                return ResourceManager.GetString("LabelPrice", resourceCulture);
            }
        }
        
        internal static string LabelAvailable {
            get {
                return ResourceManager.GetString("LabelAvailable", resourceCulture);
            }
        }
        
        internal static string LabelTotalInitial {
            get {
                return ResourceManager.GetString("LabelTotalInitial", resourceCulture);
            }
        }
        
        internal static string LabelSellerInformation {
            get {
                return ResourceManager.GetString("LabelSellerInformation", resourceCulture);
            }
        }
        
        internal static string ValueNotAvailable {
            get {
                return ResourceManager.GetString("ValueNotAvailable", resourceCulture);
            }
        }
        
        internal static string ErrorProductIdInvalid {
            get {
                return ResourceManager.GetString("ErrorProductIdInvalid", resourceCulture);
            }
        }
        
        internal static string ErrorProductNotFound {
            get {
                return ResourceManager.GetString("ErrorProductNotFound", resourceCulture);
            }
        }
        
        internal static string ErrorFailedToLoadDetailsPrefix {
            get {
                return ResourceManager.GetString("ErrorFailedToLoadDetailsPrefix", resourceCulture);
            }
        }
    }
}
