//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalyFarmar.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SellPageStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SellPageStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MalyFarmar.Resources.Strings.SellPageStrings", typeof(SellPageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string SellPageTitle {
            get {
                return ResourceManager.GetString("SellPageTitle", resourceCulture);
            }
        }
        
        internal static string AddProductToolbarItemText {
            get {
                return ResourceManager.GetString("AddProductToolbarItemText", resourceCulture);
            }
        }
        
        internal static string ProductItemPriceLabel {
            get {
                return ResourceManager.GetString("ProductItemPriceLabel", resourceCulture);
            }
        }
        
        internal static string ProductItemAvailableLabel {
            get {
                return ResourceManager.GetString("ProductItemAvailableLabel", resourceCulture);
            }
        }
        
        internal static string StatusCurrentUserError {
            get {
                return ResourceManager.GetString("StatusCurrentUserError", resourceCulture);
            }
        }
        
        internal static string StatusNoProductsSelling {
            get {
                return ResourceManager.GetString("StatusNoProductsSelling", resourceCulture);
            }
        }
        
        internal static string StatusNoProductsFoundOrError {
            get {
                return ResourceManager.GetString("StatusNoProductsFoundOrError", resourceCulture);
            }
        }
        
        internal static string StatusFailedToLoadProductsPrefix {
            get {
                return ResourceManager.GetString("StatusFailedToLoadProductsPrefix", resourceCulture);
            }
        }
        
        internal static string StatusUnexpectedErrorPrefix {
            get {
                return ResourceManager.GetString("StatusUnexpectedErrorPrefix", resourceCulture);
            }
        }
        
        internal static string StatusLoadingCancelled {
            get {
                return ResourceManager.GetString("StatusLoadingCancelled", resourceCulture);
            }
        }
    }
}
